# This is a basic workflow to help you get started with Actions

name: get anime list

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  repository_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm install

      - name: Get Data
        run: |
          node ./index.js

      - name: Diff
        run: git diff --exit-code || echo "::set-output name=DIFF_EXISTS::1"
        id: diff
      - if: steps.diff.outputs.DIFF_EXISTS
        name: Push the latest
        run: |
          DATE=$(date '+%Y-%m-%d')
          # BRANCH=update-${DATE}
          BRANCH=master
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "github-actions-bot@users.noreply.github.com"
          git add dist
          git commit -m "Update: ${DATE}"
          git push -u origin "$BRANCH"
